### ISSUE TITLE
Play video

### ISSUE THREAD

**Issue by sciepsilon** [Designist/KorpusApp#2]

**Comment by nickatomlin** [comment]
Success! Remaining to-do list for video:

- Make sure it works on Android
- Don't make it use the whole screen, e.g., try placing TextDisplay underneath
- Fix navigator

<img width="373" alt="screen shot 2017-08-22 at 1 01 08 pm" src="https://user-images.githubusercontent.com/13228316/29577607-08b3f31e-873a-11e7-88e3-669c58721685.png">

**Comment by nickatomlin** [comment]
**Note**: don't place <Video> elements inside views. They won't appear.
